tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "jesseduffield/lazygit"
tap "zegervdv/zathura"
brew "exa"
brew "lazydocker"
brew "lua-language-server"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "tmux"
brew "jesseduffield/lazygit/lazygit"
brew "zegervdv/zathura/zathura"
brew "zegervdv/zathura/zathura-pdf-poppler"
cask "alacritty"
cask "dbeaver-community"
cask "kitty"
cask "neovide"
