require("modules.nv-tree")
require("modules.nv-telescope")
require("modules.nv-colorizer")
require("modules.nv-bufferline")
require("modules.nv-lualine")
require("modules.nv-comment")
require("modules.nv-autopairs")
require("modules.nv-autotag")
-- require("modules.nv-gps")
require("modules.nv-lspsaga")
require("modules.nv-vimtex")
require("modules.nv-gitsigns")
require("modules.nv-scrollbar")
-- require("modules.nv-prettyfold")
require("modules.nv-symbolsoutline")
require("modules.nv-todocomments")
require("modules.nv-luasnip")
require("modules.nv-navic")
require("modules.nv-dap")
require("modules.nv-ufo")
-- require("modules.nv-lspsignature")
-- require("modules.nv-cyclist")
