require("modules.nv-tree")
require("modules.nv-telescope")
require("modules.nv-colorizer")
require("modules.nv-bufferline")
-- require('modules.nv-galaxyline')
require("modules.nv-lualine")
require("modules.nv-comment")
require("modules.nv-autopairs")
require("modules.nv-autotag")
require("modules.nv-gps")
require("modules.nv-lspsaga")
require("modules.nv-vimtex")
require("modules.nv-gitsigns")
require("modules.nv-scrollbar")
require("modules.nv-prettyfold")
require("modules.nv-symbolsoutline")
require("modules.nv-todocomments")
