#!/usr/bin/env sh
# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# yabai -m config window_shadow                on
yabai -m config window_border                on 
yabai -m config window_border_width          4
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier alt

# left click + drag
yabai -m config mouse_action1 move
# right click + drag
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off
# yabai -m rule --add app="^Karabiner-Elements$" manage=off


echo 'yabai configuration loaded...'
